ARG UPSTREAM_NFS_CSI_IMAGE=iregistry.baidu-int.com/cnap-cluster/nfsplugin:v4.13.2
ARG BASE_IMAGE=iregistry.baidu-int.com/baidu-base/ubuntu:resolute

FROM ${UPSTREAM_NFS_CSI_IMAGE} AS upstream

FROM ${BASE_IMAGE}

COPY --from=upstream /nfsplugin /nfsplugin
COPY --from=upstream /sbin/mount.nfs /sbin/mount.nfs
COPY --from=upstream /sbin/mount.nfs4 /sbin/mount.nfs4
COPY --from=upstream /usr/sbin/mount.nfs /usr/sbin/mount.nfs
COPY --from=upstream /usr/sbin/mount.nfs4 /usr/sbin/mount.nfs4
COPY --from=upstream /lib/x86_64-linux-gnu/libtirpc.so.3 /usr/lib/x86_64-linux-gnu/libtirpc.so.3
COPY --from=upstream /etc/netconfig /etc/netconfig

COPY dist/linux-amd64/kruise-nfs-wrapper /usr/local/bin/kruise-nfs-wrapper
COPY dist/linux-amd64/kruise-nfs-mounter /usr/local/bin/kruise-nfs-mounter
COPY build/wrapper/entrypoint.sh /usr/local/bin/kruise-nfs-entrypoint

ENTRYPOINT ["/usr/local/bin/kruise-nfs-entrypoint"]
