apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kruise-agents-nfs-csi.controllerServiceAccount" . }}
  namespace: {{ include "kruise-agents-nfs-csi.namespace" . }}
  labels:
    {{- include "kruise-agents-nfs-csi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kruise-agents-nfs-csi.nodeServiceAccount" . }}
  namespace: {{ include "kruise-agents-nfs-csi.namespace" . }}
  labels:
    {{- include "kruise-agents-nfs-csi.labels" . | nindent 4 }}
